<?php
/**
 * Plugin Name: AI ParseAble drop-in
 * Description: Captures AI crawler hits before plugins load. Generated by AI ParseAble — do not edit; it is rewritten on upgrade and removed on uninstall.
 * Version:     0.0.0
 *
 * Zero dependencies. Nothing here calls WordPress. It matches the user agent against a precompiled
 * pattern and, on a match, registers a shutdown function that appends one line to a daily queue file.
 * Non-matching requests cost a single preg_match and exit.
 *
 * @package AiParseAble
 */

// phpcs:disable WordPress.Security.ValidatedSanitizedInput -- raw request headers are matched and tab-stripped, never output; sanitising functions do not exist this early.
// phpcs:disable WordPress.WP.AlternativeFunctions -- WP_Filesystem is not loaded this early and would cost more than the whole request budget.
// phpcs:disable WordPress.PHP.NoSilencedErrors.Discouraged -- a failed append must never surface to the visitor.

defined( 'ABSPATH' ) || exit;

if ( defined( 'AI_PARSEABLE_DROP_IN' ) ) {
	return;
}
define( 'AI_PARSEABLE_DROP_IN', '0.0.0' );

$ai_parseable_config = array(); // Replaced by the plugin: AI_PARSEABLE_CONFIG.

( static function ( array $c ) {
	$ua = isset( $_SERVER['HTTP_USER_AGENT'] ) ? (string) $_SERVER['HTTP_USER_AGENT'] : '';
	if ( '' === $ua || empty( $c['pattern'] ) || empty( $c['dir'] ) || empty( $c['token'] ) ) {
		return;
	}
	$start = microtime( true );
	if ( ! preg_match( $c['pattern'], $ua, $m ) ) {
		return;
	}
	$token      = $m[1];
	$elapsed_us = (int) round( ( microtime( true ) - $start ) * 1000000 );

	register_shutdown_function(
		static function () use ( $c, $token, $elapsed_us ) {
			$status = (int) http_response_code();
			$ip     = isset( $_SERVER['REMOTE_ADDR'] ) ? (string) $_SERVER['REMOTE_ADDR'] : '';
			if ( false === filter_var( $ip, FILTER_VALIDATE_IP ) ) {
				$ip = '';
			}
			$cached = 0;
			foreach ( headers_list() as $header ) {
				if ( preg_match( '~^(x-cache|x-litespeed-cache|x-wp-rocket|cf-cache-status|x-nginx-cache|x-proxy-cache|x-srcache-fetch-status)\s*:~i', $header ) ) {
					$cached = 1;
					break;
				}
			}
			$clean = static function ( $v ) {
				return str_replace( array( "\t", "\n", "\r" ), ' ', (string) $v );
			};
			$line  = implode(
				"\t",
				array(
					gmdate( 'Y-m-d H:i:s' ),
					$clean( $token ),
					$ip,
					$clean( substr( isset( $_SERVER['REQUEST_METHOD'] ) ? $_SERVER['REQUEST_METHOD'] : 'GET', 0, 10 ) ),
					$clean( substr( isset( $_SERVER['REQUEST_URI'] ) ? $_SERVER['REQUEST_URI'] : '/', 0, 1024 ) ),
					$clean( substr( isset( $_SERVER['HTTP_HOST'] ) ? $_SERVER['HTTP_HOST'] : '', 0, 255 ) ),
					$status > 0 ? $status : 200,
					$cached,
					$elapsed_us,
				)
			) . "\n";

			// Orphan guard: if the plugin was deleted without deactivating, stop writing rather than
			// filling the queue with files nobody will ingest. Checked only on crawler hits.
			if ( ! empty( $c['plugin'] ) && ! is_file( $c['plugin'] ) ) {
				return;
			}
			$file = rtrim( $c['dir'], '/' ) . '/' . gmdate( 'Y-m-d' ) . '-' . $c['token'] . '.log';
			if ( ! is_dir( $c['dir'] ) && ! @mkdir( $c['dir'], 0755, true ) ) {
				return;
			}
			if ( is_file( $file ) && filesize( $file ) > (int) $c['max_bytes'] ) {
				return; // Self-defence: a flood must never fill the disk.
			}
			@file_put_contents( $file, $line, FILE_APPEND | LOCK_EX );
		}
	);
} )( $ai_parseable_config );
